config/routes.rb
routes = lambda do
  match '/email_to_friend/:type/:id' => 'email_sender#send_mail', as: :email_to_friend, via: [:get, :post]

  namespace :admin do
    resource :captcha_settings
  end
end

if Spree::Core::Engine.respond_to?(:add_routes)
  Spree::Core::Engine.add_routes(&routes)
else
  Spree::Core::Engine.routes.draw(&routes)
end

app/controllers/spree/admin/captcha_settings_controller.rb
module Spree
  module Admin
    class CaptchaSettingsController < BaseController
      def update
        params[:preferences].each do |key, value|
          Spree::Captcha::Config.set_preference(key, value)
        end

        respond_to do |format|
          format.html { redirect_to edit_admin_captcha_settings_path }
        end
      end
    end
  end
end

app/views/admin/captcha_settings/edit.html.erb
<%= render :partial => 'admin/shared/configuration_menu' %>

<h1><%= t('captcha.captcha_settings') %></h1>

<%= form_tag(admin_captcha_settings_path, :method => :put) do -%>
  <p>
    <label><%= t('captcha.use_captcha') %>:</label>
    <label><%= radio_button_tag('preferences[use_captcha]', true, Spree::Captcha::Config[:use_captcha])%> Yes</label> &nbsp;&nbsp;
    <label><%= radio_button_tag('preferences[use_captcha]', false, !Spree::Captcha::Config[:use_captcha])%> No</label>
  </p>
  <p>
    <label><%= t('captcha.public_key') %>:</label>
    <%= text_field_tag('preferences[public_key]', Spree::Captcha::Config[:public_key], :size => 40) %>
  </p>
  <p>
    <label><%= t('captcha.private_key') %>:</label>
    <%= text_field_tag('preferences[private_key]', Spree::Captcha::Config[:private_key], :size => 40)%>
  </p>
  <p>
    <label><%= t('captcha.theme') %>:</label>
    <%= select_tag('preferences[theme]', options_for_select(CaptchaConfiguration::THEMES, Spree::Captcha::Config[:theme])) %>
  </p>
  <p class="form-buttons">
    <%= button t(:update) %>
    <%= t(:or) %> <%= link_to t(:cancel), admin_captcha_settings_url %>
  </p>
<% end -%>

app/views/admin/captcha_settings/show.html.erb
<%= render :partial => 'admin/shared/configuration_menu' %>

<h1><%= t('captcha.captcha_settings') %></h1>

<table>
  <tr>
    <th scope="row"><%= t('captcha.use_captcha') %>:</th>
    <td style="color: <%= Spree::Captcha::Config[:use_captcha] ? 'green' : 'red' %>;"><%= Spree::Captcha::Config[:use_captcha] ? 'Yes' : 'No' %></td>
  </tr>
  <tr>
    <th scope="row"><%= t('captcha.public_key') %>:</th>
    <td><%= Spree::Captcha::Config[:public_key] %></td>
  </tr>
  <tr>
    <th scope="row"><%= t('captcha.private_key') %>:</th>
    <td><%= Spree::Captcha::Config[:private_key] %></td>
  </tr>
  <tr>
    <th scope="row"><%= t('captcha.theme') %>:</th>
    <td><%= Spree::Captcha::Config[:theme] %></td>
  </tr>
</table>

<p>
  <%= link_to_with_icon('edit', t(:edit), edit_admin_captcha_settings_path) %>
</p>